flowchart TD
    A([Read path SQL file])
    A --> B[Parse schema using SqlSchemaParser]
    B --> C[Show the list of tables from Schema]
    C --> D[Request tables to show]
    D --> E[Print filtered tables as ASCII]
    E --> F[End]